---
- name: Install PostgreSQL
  hosts: ubuntu_servers
  become: yes

  tasks:
    # install postgresql on ubuntu
    - name: Install PostgreSQL
      package:
        name: postgresql
        state: present

    - name: change postgres network binding
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '# listen_addresses'
        line: "listen_addresses = '*'"

    - name: change postgres pg hba access
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        regexp: 'host  all  all 0.0.0.0/0 md5'
        line: 'host  all  all 0.0.0.0/0 md5'

    - name: start postgresql server
      service:
        enabled: yes
        name: postgresql
        state: restarted

    - name: Install psycopg2
      package:  
        name: python3-psycopg2
        state: present
        update_cache: yes



      